apiVersion: v1
kind: Pod
metadata: 
        name: myfirstpod
spec:
        containers:
                - name: myapp
                  image: nginx
                  volumeMounts:
                  - name: html
                    mountPath: /usr/share/nginx/html
        volumes:
                - name: html
                  emptyDir: {}
